import type { Template } from "./types";

const now = 1_700_000_000_000;

export const SEED_TEMPLATES: Template[] = [
  {
    id: "seed_4x4",
    name: "4×4 terskel",
    sport: "running",
    environment: "treadmill",
    isSeed: true,
    createdAt: now - 5,
    updatedAt: now - 5,
    series: [
      {
        id: "seed_4x4_s1",
        kind: "work",
        durationSec: 240,
        restSec: 120,
        reps: 4,
        targetSpeedKmh: 12,
        targetZone: 4,
      },
    ],
  },
  {
    id: "seed_pyramid",
    name: "Pyramide 1–2–3–2–1",
    sport: "running",
    environment: "outdoor",
    isSeed: true,
    createdAt: now - 4,
    updatedAt: now - 4,
    series: [
      {
        id: "seed_pyr_1",
        kind: "work",
        durationSec: 60,
        restSec: 60,
        reps: 1,
        targetSpeedKmh: 14,
        targetZone: 5,
      },
      {
        id: "seed_pyr_2",
        kind: "work",
        durationSec: 120,
        restSec: 60,
        reps: 1,
        targetSpeedKmh: 13.5,
        targetZone: 4,
      },
      {
        id: "seed_pyr_3",
        kind: "work",
        durationSec: 180,
        restSec: 90,
        reps: 1,
        targetSpeedKmh: 13,
        targetZone: 4,
      },
      {
        id: "seed_pyr_4",
        kind: "work",
        durationSec: 120,
        restSec: 60,
        reps: 1,
        targetSpeedKmh: 13.5,
        targetZone: 4,
      },
      {
        id: "seed_pyr_5",
        kind: "work",
        durationSec: 60,
        restSec: 0,
        reps: 1,
        targetSpeedKmh: 14,
        targetZone: 5,
      },
    ],
  },
  {
    id: "seed_fullbody",
    name: "Fullkropp A",
    sport: "strength",
    environment: "gym",
    programTag: "Fullkropp",
    isSeed: true,
    createdAt: now - 3,
    updatedAt: now - 3,
    series: [
      {
        id: "seed_fb_1",
        kind: "work",
        durationSec: 0,
        restSec: 90,
        reps: 4,
        exerciseName: "Knebøy",
        targetReps: 8,
        targetWeightKg: 50,
        muscleGroup: "legs",
        equipment: "barbell",
        libraryId: "ex_squat",
        notes: "Hofte dypt, knær ut",
        targetRpe: 8,
      },
      {
        id: "seed_fb_2",
        kind: "work",
        durationSec: 0,
        restSec: 90,
        reps: 4,
        exerciseName: "Benkpress",
        targetReps: 8,
        targetWeightKg: 40,
        muscleGroup: "push",
        equipment: "barbell",
        libraryId: "ex_bench",
        targetRpe: 8,
      },
      {
        id: "seed_fb_3",
        kind: "work",
        durationSec: 0,
        restSec: 75,
        reps: 3,
        exerciseName: "Roing",
        targetReps: 10,
        targetWeightKg: 35,
        muscleGroup: "pull",
        equipment: "barbell",
        libraryId: "ex_row",
        targetRpe: 7,
      },
      {
        id: "seed_fb_4",
        kind: "work",
        durationSec: 0,
        restSec: 60,
        reps: 3,
        exerciseName: "Planke",
        targetReps: 45,
        muscleGroup: "core",
        equipment: "bodyweight",
        libraryId: "ex_plank",
        notes: "Reps = sekunder hold",
      },
    ],
  },
  {
    id: "seed_push",
    name: "Push-dag",
    sport: "strength",
    environment: "home",
    programTag: "Push",
    isSeed: true,
    createdAt: now - 2,
    updatedAt: now - 2,
    series: [
      {
        id: "seed_push_1",
        kind: "work",
        durationSec: 0,
        restSec: 60,
        reps: 3,
        exerciseName: "Armhevinger",
        targetReps: 12,
        muscleGroup: "push",
        equipment: "bodyweight",
        libraryId: "ex_pushup",
      },
      {
        id: "seed_push_2",
        kind: "work",
        durationSec: 0,
        restSec: 60,
        reps: 3,
        exerciseName: "Pike push-ups",
        targetReps: 8,
        muscleGroup: "push",
        equipment: "bodyweight",
        libraryId: "ex_pike",
      },
      {
        id: "seed_push_3",
        kind: "work",
        durationSec: 0,
        restSec: 45,
        reps: 3,
        exerciseName: "Dips (stol)",
        targetReps: 10,
        muscleGroup: "push",
        equipment: "bodyweight",
        libraryId: "ex_dips",
        notes: "Stol eller parallel bars",
      },
    ],
  },
  {
    id: "seed_hips",
    name: "Hofter & ankler",
    sport: "mobility",
    environment: "home",
    isSeed: true,
    createdAt: now - 1,
    updatedAt: now - 1,
    series: [
      {
        id: "seed_hip_1",
        kind: "work",
        durationSec: 40,
        restSec: 10,
        reps: 4,
        exerciseName: "90/90 sit",
        targetZone: 1,
      },
      {
        id: "seed_hip_2",
        kind: "work",
        durationSec: 30,
        restSec: 10,
        reps: 4,
        exerciseName: "Ankel rock",
        targetZone: 1,
      },
      {
        id: "seed_hip_3",
        kind: "work",
        durationSec: 45,
        restSec: 15,
        reps: 3,
        exerciseName: "World's greatest stretch",
        targetZone: 1,
      },
    ],
  },
];
