/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as TemplatesNewRouteImport } from './routes/templates.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TemplatesIdEditRouteImport } from './routes/templates.$id.edit'
import { Route as TemplatesIdStartRouteImport } from './routes/templates.$id.start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesNewRoute = TemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdEditRoute = TemplatesIdEditRouteImport.update({
  id: '/templates/$id/edit',
  path: '/templates/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdStartRoute = TemplatesIdStartRouteImport.update({
  id: '/templates/$id/start',
  path: '/templates/$id/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/session/$id': typeof SessionIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/start': typeof TemplatesIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/session/$id': typeof SessionIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/start': typeof TemplatesIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/history/$id': typeof HistoryIdRoute
  '/session/$id': typeof SessionIdRoute
  '/templates/new': typeof TemplatesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/templates/$id/edit': typeof TemplatesIdEditRoute
  '/templates/$id/start': typeof TemplatesIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/login'
    | '/settings'
    | '/history/$id'
    | '/session/$id'
    | '/templates/new'
    | '/api/auth/$'
    | '/templates/$id/edit'
    | '/templates/$id/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/login'
    | '/settings'
    | '/history/$id'
    | '/session/$id'
    | '/templates/new'
    | '/api/auth/$'
    | '/templates/$id/edit'
    | '/templates/$id/start'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/login'
    | '/settings'
    | '/history/$id'
    | '/session/$id'
    | '/templates/new'
    | '/api/auth/$'
    | '/templates/$id/edit'
    | '/templates/$id/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SessionIdRoute: typeof SessionIdRoute
  TemplatesNewRoute: typeof TemplatesNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TemplatesIdEditRoute: typeof TemplatesIdEditRoute
  TemplatesIdStartRoute: typeof TemplatesIdStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/new': {
      id: '/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof TemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/edit': {
      id: '/templates/$id/edit'
      path: '/templates/$id/edit'
      fullPath: '/templates/$id/edit'
      preLoaderRoute: typeof TemplatesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id/start': {
      id: '/templates/$id/start'
      path: '/templates/$id/start'
      fullPath: '/templates/$id/start'
      preLoaderRoute: typeof TemplatesIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SessionIdRoute: SessionIdRoute,
  TemplatesNewRoute: TemplatesNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TemplatesIdEditRoute: TemplatesIdEditRoute,
  TemplatesIdStartRoute: TemplatesIdStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
